Created Login, Signup and home page
madhvikokil/React-Book-Store-Assignment pull request #1
Opened 2021-09-29 13:20 UTC by madhvikokil

2021-10-13 05:41 UTC, chetanbura requested changes
Please cover below things
1. Handle Validations in HOC only
2. Optimize code wherever mentions
3. Optimize with metadata for listing records create HOC if possible

2021-10-13 05:41 UTC, chetanbura commented on src/App.js
> +  }
else condition is best for customer

2021-10-13 05:41 UTC, chetanbura commented on src/App.js
> +      });
move this function outside and use parameter for component path

2021-10-13 05:41 UTC, chetanbura commented on src/App.js
> +      <Suspense fallback={<p>Loading...</p>}>
Instead using suspense directly, create 1 component for error boundary along with suspense and use that here so you can catch error for that route only

2021-10-13 05:41 UTC, chetanbura commented on src/Hoc/formElement.js
> +            errorMessages={["Field Required"]}
is every field is required, these values suppose to be from props

2021-10-13 05:41 UTC, chetanbura commented on src/Hoc/formElement.js
> +
And try to add common validation logic in this hoc

2021-10-13 05:41 UTC, chetanbura commented on src/component/navMenu.js
> +          />
Optimize this with metadata and using map

2021-10-13 05:41 UTC, chetanbura commented on src/container/addBook.js
> +    // }
Remove unwanted code

2021-10-13 05:41 UTC, chetanbura commented on src/container/addBook.js
> +          this.setState({ title: updateTitle, description: updateDescription, status: updateStatus, author: updateAuthor, price: updatePrice, id: updateId, discount: updateDiscount, userType: updateU
optimize this

2021-10-13 05:41 UTC, chetanbura commented on src/container/addBook.js
> +        uid: nextProps.bookDetail.uid
optimize this

2021-10-13 05:41 UTC, chetanbura commented on src/container/addBook.js
> +                      id: 'form-input-control-discount', label: 'Discount', placeholder: 'Discount', name: 'discount', onChange: this.handleChange, value: discount, readOnly: isEdit === 'view' ? true
optimize this

2021-10-13 05:41 UTC, chetanbura commented on src/container/auth/login.js
> +  }
create validation helper where all validations can be handeled

2021-10-13 05:41 UTC, chetanbura commented on src/container/auth/login.js
> +                </div>
optimize here and try to handle orChange in hoc only

2021-10-13 05:41 UTC, chetanbura commented on src/container/auth/signup.js
> +
duplicate code

2021-10-13 05:41 UTC, chetanbura commented on src/container/auth/signup.js
> +              disabled={this.state.firstName === '' || this.state.lastName === '' || this.state.email === '' || this.state.password === ''}>Sign Up
optimize

2021-10-13 05:41 UTC, chetanbura commented on src/container/bookFunctionality.js
> +            <React.Fragment>
`<React.Fragment>` to `<>`   all pages/places

2021-10-13 05:41 UTC, chetanbura commented on src/container/bookList.js
> +                    <Table.HeaderCell>Action</Table.HeaderCell>
optimize with map and metadata

2021-10-13 05:41 UTC, chetanbura commented on src/container/bookList.js
> +                        <Table.Cell>{book.status}</Table.Cell>
optimize with map and metadata

2021-10-13 05:41 UTC, chetanbura commented on src/container/homePage.js
> +            <Table.Cell><Button onClick={() => placeMyOrder(book)}>Place Order</Button></Table.Cell>
optimize with map and metadata

2021-10-13 05:41 UTC, chetanbura commented on src/container/myOrders.js
> +                        </Table.Row>
optimize with map and metadata

2021-10-13 05:41 UTC, chetanbura commented on src/container/order.js
> +                            <Button onClick={() => props.updateOrderByAdmin(order)}>Pending -> Complete</Button>}</Table.Cell>
optimize with map and metadata

2021-10-13 05:41 UTC, chetanbura commented on src/container/userList.js
> +                        ))}
optimize with map and metadata

2021-10-25 07:41 UTC, merged

2021-10-25 07:59 UTC, madhvikokil commented on src/App.js
> +  }
done

2021-10-25 07:59 UTC, madhvikokil commented on src/App.js
> +      });
done

2021-10-25 07:59 UTC, madhvikokil commented on src/App.js
> +      <Suspense fallback={<p>Loading...</p>}>
done

2021-10-25 07:59 UTC, madhvikokil commented on src/Hoc/formElement.js
> +            errorMessages={["Field Required"]}
done

2021-10-25 07:59 UTC, madhvikokil commented on src/Hoc/formElement.js
> +
done

2021-10-25 08:00 UTC, madhvikokil commented on src/component/navMenu.js
> +          />
done

2021-10-25 08:00 UTC, madhvikokil commented on src/container/addBook.js
> +    // }
done

2021-10-25 08:01 UTC, madhvikokil commented on src/container/addBook.js
> +          this.setState({ title: updateTitle, description: updateDescription, status: updateStatus, author: updateAuthor, price: updatePrice, id: updateId, discount: updateDiscount, userType: updateU
done

2021-10-25 08:01 UTC, madhvikokil commented on src/container/addBook.js
> +        uid: nextProps.bookDetail.uid
done

2021-10-25 08:01 UTC, madhvikokil commented on src/container/auth/login.js
> +                </div>
done

2021-10-25 08:01 UTC, madhvikokil commented on src/container/addBook.js
> +                      id: 'form-input-control-discount', label: 'Discount', placeholder: 'Discount', name: 'discount', onChange: this.handleChange, value: discount, readOnly: isEdit === 'view' ? true
done

2021-10-25 08:01 UTC, madhvikokil commented on src/container/auth/login.js
> +  }
done

2021-10-25 08:01 UTC, madhvikokil commented on src/container/auth/signup.js
> +
done

2021-10-25 08:01 UTC, madhvikokil commented on src/container/auth/signup.js
> +              disabled={this.state.firstName === '' || this.state.lastName === '' || this.state.email === '' || this.state.password === ''}>Sign Up
done

2021-10-25 08:03 UTC, madhvikokil commented on src/container/bookList.js
> +                        <Table.Cell>{book.status}</Table.Cell>
done

2021-10-25 08:03 UTC, madhvikokil commented on src/container/homePage.js
> +            <Table.Cell><Button onClick={() => placeMyOrder(book)}>Place Order</Button></Table.Cell>
done

2021-10-25 08:03 UTC, madhvikokil commented on src/container/myOrders.js
> +                        </Table.Row>
done

2021-10-25 08:05 UTC, madhvikokil commented on src/container/order.js
> +                            <Button onClick={() => props.updateOrderByAdmin(order)}>Pending -> Complete</Button>}</Table.Cell>
done

2021-10-25 08:05 UTC, madhvikokil commented on src/container/userList.js
> +                        ))}
done

2021-10-25 08:10 UTC, madhvikokil commented on src/container/bookFunctionality.js
> +            <React.Fragment>
done

2021-10-25 08:10 UTC, madhvikokil commented on src/container/bookList.js
> +                    <Table.HeaderCell>Action</Table.HeaderCell>
done